rename Abra.png Abra.png
rename aerodactyl.png Aerodactyl.png
rename Agatha.png Agatha.png
rename Alakazam.png Alakazam.png
rename arbok.png Arbok.png
rename Arcanine.png Arcanine.png
rename articuno.png Articuno.png
rename beedrill.png Beedrill.png
rename bellsprout.png Bellsprout.png
rename Blaine.png Blaine.png
rename blastoise.png Blastoise.png
rename Brock.png Brock.png
rename Bruno.png Bruno.png
rename bulbasaur.png Bulbasaur.png
rename butterfree.png Butterfree.png
rename caterpie.png Caterpie.png
rename chansey.png Chansey.png
rename charizard.png Charizard.png
rename charmander.png Charmander.png
rename charmeleon.png Charmeleon.png
rename clefable.png Clefable.png
rename clefairy.png Clefairy.png
rename cloyster.png Cloyster.png
rename cubone.png Cubone.png
rename dewgong.png Dewgong.png
rename diglett.png Diglett.png
rename ditto.png Ditto.png
rename dodrio.png Dodrio.png
rename doduo.png Doduo.png
rename dragonair.png Dragonair.png
rename Dragonite.png Dragonite.png
rename dratini.png Dratini.png
rename drowzee.png Drowzee.png
rename Dugtrio.png Dugtrio.png
rename eevee.png Eevee.png
rename ekans.png Ekans.png
rename electabuzz.png Electabuzz.png
rename electrode.png Electrode.png
rename Erika.png Erika.png
rename exeggcute.png Exeggcute.png
rename exeggutor.png Exeggutor.png
rename Farfetchd.png Farfetchd.png
rename fearow.png Fearow.png
rename flareon.png Flareon.png
rename gastly.png Gastly.png
rename gengar.png Gengar.png
rename Geodude.png Geodude.png
rename Giovanni.png Giovanni.png
rename Gloom.png Gloom.png
rename golbat.png Golbat.png
rename goldeen.png Goldeen.png
rename golduck.png Golduck.png
rename golem.png Golem.png
rename graveler.png Graveler.png
rename grimer.png Grimer.png
rename growlithe.png Growlithe.png
rename gyarados.png Gyarados.png
rename haunter.png Haunter.png
rename hitmonchan.png Hitmonchan.png
rename hitmonlee.png Hitmonlee.png
rename horsea.png Horsea.png
rename hypno.png Hypno.png
rename ivysaur.png Ivysaur.png
rename jigglypuff.png Jigglypuff.png
rename jolteon.png Jolteon.png
rename jynx.png Jynx.png
rename kabuto.png Kabuto.png
rename kabutops.png Kabutops.png
rename Kadabra.png Kadabra.png
rename kakuna.png Kakuna.png
rename kangaskhan.png Kangaskhan.png
rename kingler.png Kingler.png
rename koffing.png Koffing.png
rename Koga.png Koga.png
rename krabby.png Krabby.png
rename Lance.png Lance.png
rename lapras.png Lapras.png
rename lickitung.png Lickitung.png
rename logo.png Logo.png
rename Lorelei.png Lorelei.png
rename machamp.png Machamp.png
rename machoke.png Machoke.png
rename machop.png Machop.png
rename magikarp.png Magikarp.png
rename magmar.png Magmar.png
rename magnemite.png Magnemite.png
rename magneton.png Magneton.png
rename mankey.png Mankey.png
rename marowak.png Marowak.png
rename meowth.png Meowth.png
rename metapod.png Metapod.png
rename mew.png Mew.png
rename mewtwo.png Mewtwo.png
rename Misty.png Misty.png
rename moltres.png Moltres.png
rename Mr-mime.png Mr-Mime.png
rename muk.png Muk.png
rename Nidoking.png Nidoking.png
rename Nidoqueen.png Nidoqueen.png
rename Nidoran-F.png Nidoran-F.png
rename Nidoran-M.png Nidoran-M.png
rename nidorina.png Nidorina.png
rename nidorino.png Nidorino.png
rename Ninetales.png Ninetales.png
rename oddish.png Oddish.png
rename omanyte.png Omanyte.png
rename omastar.png Omastar.png
rename Onix.png Onix.png
rename paras.png Paras.png
rename parasect.png Parasect.png
rename Persian.png Persian.png
rename pidgeot.png Pidgeot.png
rename pidgeotto.png Pidgeotto.png
rename pidgey.png Pidgey.png
rename pikachu.png Pikachu.png
rename pinsir.png Pinsir.png
rename poliwag.png Poliwag.png
rename poliwhirl.png Poliwhirl.png
rename poliwrath.png Poliwrath.png
rename ponyta.png Ponyta.png
rename porygon.png Porygon.png
rename primeape.png Primeape.png
rename psyduck.png Psyduck.png
rename Raichu.png Raichu.png
rename Rapidash.png Rapidash.png
rename raticate.png Raticate.png
rename rattata.png Rattata.png
rename Rhydon.png Rhydon.png
rename Rhyhorn.png Rhyhorn.png
rename Sabrina.png Sabrina.png
rename sandshrew.png Sandshrew.png
rename sandslash.png Sandslash.png
rename scyther.png Scyther.png
rename seadra.png Seadra.png
rename seaking.png Seaking.png
rename seel.png Seel.png
rename shellder.png Shellder.png
rename slowbro.png Slowbro.png
rename slowpoke.png Slowpoke.png
rename snorlax.png Snorlax.png
rename spearow.png Spearow.png
rename squirtle.png Squirtle.png
rename Starmie.png Starmie.png
rename Staryu.png Staryu.png
rename Surge.png Surge.png
rename Tangela.png Tangela.png
rename tauros.png Tauros.png
rename tentacool.png Tentacool.png
rename tentacruel.png Tentacruel.png
rename vaporeon.png Vaporeon.png
rename Venomoth.png Venomoth.png
rename Venonat.png Venonat.png
rename venusaur.png Venusaur.png
rename victreebel.png Victreebel.png
rename vileplume.png Vileplume.png
rename voltorb.png Voltorb.png
rename vulpix.png Vulpix.png
rename wartortle.png Wartortle.png
rename weedle.png Weedle.png
rename Weepinbell.png Weepinbell.png
rename weezing.png Weezing.png
rename wigglytuff.png Wigglytuff.png
rename zapdos.png Zapdos.png
rename zubat.png Zubat.png
